/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Radio;

import java.awt.Color;

/**
 *
 * @author Ana Lucía Hernández (17138). Mario Sarmientos (17055)
 */
public class RadioUI extends javax.swing.JFrame {

    /**
     * Creates new form RadioUI
     */
    douglas radio;
    
    public RadioUI() {
        initComponents();
        radio = new Radio();
        botonFM.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        emisora1 = new javax.swing.JButton();
        emisora2 = new javax.swing.JButton();
        emisora3 = new javax.swing.JButton();
        emisora4 = new javax.swing.JButton();
        emisora5 = new javax.swing.JButton();
        emisora6 = new javax.swing.JButton();
        estacionSiguiente = new javax.swing.JButton();
        estacionAnterior1 = new javax.swing.JButton();
        botonAM = new javax.swing.JButton();
        botonFM = new javax.swing.JButton();
        labelEmisora = new javax.swing.JLabel();
        botonOnOff = new javax.swing.JToggleButton();
        emisora7 = new javax.swing.JButton();
        emisora8 = new javax.swing.JButton();
        emisora9 = new javax.swing.JButton();
        emisora10 = new javax.swing.JButton();
        emisora11 = new javax.swing.JButton();
        emisora12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emisora1.setText("1");

        emisora2.setText("2");

        emisora3.setText("3");

        emisora4.setText("4");

        emisora5.setText("5");

        emisora6.setText("6");

        estacionSiguiente.setText(">");
        estacionSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionSiguienteActionPerformed(evt);
            }
        });

        estacionAnterior1.setText("<");
        estacionAnterior1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estacionAnterior1ActionPerformed(evt);
            }
        });

        botonAM.setText("AM");
        botonAM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAMActionPerformed(evt);
            }
        });

        botonFM.setText("FM");
        botonFM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFMActionPerformed(evt);
            }
        });

        labelEmisora.setFont(new java.awt.Font("Lucida Grande", 0, 48)); // NOI18N
        labelEmisora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmisora.setText("87.9   FM");
        labelEmisora.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonOnOff.setForeground(new java.awt.Color(0, 255, 102));
        botonOnOff.setText("ON");
        botonOnOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOnOffActionPerformed(evt);
            }
        });

        emisora7.setText("7");

        emisora8.setText("8");

        emisora9.setText("9");

        emisora10.setText("10");

        emisora11.setText("11");

        emisora12.setText("12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(546, Short.MAX_VALUE)
                .addComponent(estacionAnterior1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estacionSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botonOnOff)
                        .addGap(42, 42, 42)
                        .addComponent(labelEmisora, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonFM, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonAM, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emisora7)
                                .addGap(18, 18, 18)
                                .addComponent(emisora8)
                                .addGap(18, 18, 18)
                                .addComponent(emisora9)
                                .addGap(18, 18, 18)
                                .addComponent(emisora10)
                                .addGap(18, 18, 18)
                                .addComponent(emisora11)
                                .addGap(18, 18, 18)
                                .addComponent(emisora12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(emisora1)
                                .addGap(18, 18, 18)
                                .addComponent(emisora2)
                                .addGap(18, 18, 18)
                                .addComponent(emisora3)
                                .addGap(18, 18, 18)
                                .addComponent(emisora4)
                                .addGap(18, 18, 18)
                                .addComponent(emisora5)
                                .addGap(18, 18, 18)
                                .addComponent(emisora6)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap(48, Short.MAX_VALUE)
                                .addComponent(botonAM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonFM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(botonOnOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estacionSiguiente)
                            .addComponent(estacionAnterior1))
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelEmisora, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emisora1)
                    .addComponent(emisora2)
                    .addComponent(emisora3)
                    .addComponent(emisora4)
                    .addComponent(emisora5)
                    .addComponent(emisora6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emisora7)
                    .addComponent(emisora8)
                    .addComponent(emisora9)
                    .addComponent(emisora10)
                    .addComponent(emisora11)
                    .addComponent(emisora12))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonOnOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOnOffActionPerformed
        if (botonOnOff.isSelected())
        {
            botonOnOff.setText("OFF");
            botonOnOff.setForeground(Color.red);
            jPanel1.setEnabled(false);
        }
        else
        {
            botonOnOff.setText("ON");
            botonOnOff.setForeground(Color.green);
            jPanel1.setEnabled(true);
        }
    }//GEN-LAST:event_botonOnOffActionPerformed

    private void botonAMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAMActionPerformed
        // TODO add your handling code here:
        if (botonFM.getBackground().equals(Color.DARK_GRAY))
        {
            labelEmisora.setText(String.valueOf(radio.Switch()) + "   AM");
            botonFM.setBackground(Color.LIGHT_GRAY);
            botonAM.setBackground(Color.DARK_GRAY);
        }
            
        
    }//GEN-LAST:event_botonAMActionPerformed

    private void botonFMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFMActionPerformed
        if (botonAM.getBackground().equals(Color.DARK_GRAY))
        {
            labelEmisora.setText(String.valueOf(radio.Switch()) + "   FM");
            botonAM.setBackground(Color.LIGHT_GRAY);
            botonFM.setBackground(Color.DARK_GRAY);
        }
    }//GEN-LAST:event_botonFMActionPerformed

    private void estacionSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionSiguienteActionPerformed
        // TODO add your handling code here:
            
        if (botonAM.getBackground().equals(Color.DARK_GRAY))
        {
            labelEmisora.setText(String.valueOf(radio.siguiente(Float.parseFloat(labelEmisora.getText().substring(0, labelEmisora.getText().indexOf(" "))))) + "   AM");
        }
        else
        {
            labelEmisora.setText(String.valueOf(radio.siguiente(Float.parseFloat(labelEmisora.getText().substring(0, labelEmisora.getText().indexOf(" "))))) + "   FM");
        }
    }//GEN-LAST:event_estacionSiguienteActionPerformed

    private void estacionAnterior1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estacionAnterior1ActionPerformed
        if (botonAM.getBackground().equals(Color.DARK_GRAY))
        {
            labelEmisora.setText(String.valueOf(radio.anterior(Float.parseFloat(labelEmisora.getText().substring(0, labelEmisora.getText().indexOf(" "))))) + "   AM");
        }
        else
        {
            labelEmisora.setText(String.valueOf(radio.anterior(Float.parseFloat(labelEmisora.getText().substring(0, labelEmisora.getText().indexOf(" "))))) + "   FM");
        }
    }//GEN-LAST:event_estacionAnterior1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAM;
    private javax.swing.JButton botonFM;
    private javax.swing.JToggleButton botonOnOff;
    private javax.swing.JButton emisora1;
    private javax.swing.JButton emisora10;
    private javax.swing.JButton emisora11;
    private javax.swing.JButton emisora12;
    private javax.swing.JButton emisora2;
    private javax.swing.JButton emisora3;
    private javax.swing.JButton emisora4;
    private javax.swing.JButton emisora5;
    private javax.swing.JButton emisora6;
    private javax.swing.JButton emisora7;
    private javax.swing.JButton emisora8;
    private javax.swing.JButton emisora9;
    private javax.swing.JButton estacionAnterior1;
    private javax.swing.JButton estacionSiguiente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelEmisora;
    // End of variables declaration//GEN-END:variables
}
